ETISS 0.8.0: etiss::System Class Reference
etiss::System Class Reference abstract
System Interface for the basic system IO operations and time synchronization.
#include <System.h>
Public Member Functions
virtual ~System ()
virtual etiss::int32 iread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint32 len)=0
Instruction read operation.
virtual etiss::int32 iwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)=0
Instruction write operation.
virtual etiss::int32 dread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)=0
Data read operation.
virtual etiss::int32 dwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)=0
Data write operation.
virtual etiss::int32 dbg_read (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)=0
Debug read operation.
virtual etiss::int32 dbg_write (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)=0
Debug write operation.
virtual void syncTime (ETISS_CPU *cpu)=0
Synchronize simulation time.
Detailed Description
System Interface for the basic system IO operations and time synchronization.
Systems that are model around a CPU model, for the memory and peripherals need to implement this interface in order to be simulated with ETISS. These method are called by ETISS if required.
See also
etiss::CPUCore
Note
For increased performance use the ETISS_System structure instead.
Definition at line 76 of file System.h.
Constructor & Destructor Documentation
~System()
virtual etiss::System::~System () inline virtual
Definition at line 79 of file System.h.
References dbg_read(), dbg_write(), dread(), dwrite(), iread(), iwrite(), and syncTime().
Member Function Documentation
dbg_read()
virtual etiss::int32 etiss::System::dbg_read (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) pure virtual
Debug read operation.
This method should implement a debug read operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Note
The read debug operation is used for the instruction fetches required for generating the code blocks.
Parameters
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implemented in etiss::SimpleSystem, and etiss::DebugSystem.
Referenced by etiss::SimpleSystem::~SimpleSystem(), and ~System().
dbg_write()
virtual etiss::int32 etiss::System::dbg_write (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) pure virtual
Debug write operation.
This method should implement a debug write operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Parameters
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred
Implemented in etiss::SimpleSystem, and etiss::DebugSystem.
Referenced by etiss::SimpleSystem::~SimpleSystem(), and ~System().
dread()
virtual etiss::int32 etiss::System::dread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) pure virtual
Data read operation.
This method should implement a data read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implemented in etiss::SimpleSystem, and etiss::DebugSystem.
Referenced by etiss::SimpleSystem::~SimpleSystem(), and ~System().
dwrite()
virtual etiss::int32 etiss::System::dwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) pure virtual
Data write operation.
This method should implement a data write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implemented in etiss::SimpleSystem, and etiss::DebugSystem.
Referenced by etiss::SimpleSystem::~SimpleSystem(), and ~System().
iread()
virtual etiss::int32 etiss::System::iread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint32 len) pure virtual
Instruction read operation.
This method should implement an instruction read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the instruction should be read.
len The length of the instruction in bytes.
Returns
0 if no error occurred
Implemented in etiss::SimpleSystem, and etiss::DebugSystem.
Referenced by etiss::SimpleSystem::~SimpleSystem(), and ~System().
iwrite()
virtual etiss::int32 etiss::System::iwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) pure virtual
Instruction write operation.
This method should implement an instruction write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the instruction should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the instruction in bytes.
Returns
0 if no error occurred.
Implemented in etiss::SimpleSystem, and etiss::DebugSystem.
Referenced by etiss::SimpleSystem::~SimpleSystem(), and ~System().
syncTime()
virtual void etiss::System::syncTime (ETISS_CPU * cpu) pure virtual
Synchronize simulation time.
This method should implement the synchronization between the simulation time of the system and the CPU. This function call should allow the system to catch up with the CPU.
See also
etiss::ETISS_CPU
Parameters
cpu Pointer to the CPU structure, for which the synchronization should be performed.
Implemented in etiss::SimpleSystem, and etiss::DebugSystem.
Referenced by etiss::SimpleSystem::~SimpleSystem(), and ~System().
The documentation for this class was generated from the following file:
/home/travis/build/tum-ei-eda/etiss/include/etiss/System.h