ETISS 0.8.0: etiss::plugin::gdb::BreakpointDB Class Reference
etiss::plugin::gdb::BreakpointDB Class Reference
structure to store breakpoints
#include <GDBServer.h>
Public Member Functions
BreakpointDB ()
bool isEmpty ()
etiss::uint32 get (etiss::uint64 addr)
void set (etiss::uint64 addr, etiss::uint32 val)
Private Attributes
etiss::uint32 **** instrbrkpt_
important: index maps are reversed to instruction pointer e.g pointer(0x0102030405060708) [POINTER != ADDRESS] -> instrbrkpt_[0x0708][0x0506][0x0304][0x0201]
Detailed Description
structure to store breakpoints
Definition at line 79 of file GDBServer.h.
Constructor & Destructor Documentation
BreakpointDB()
BreakpointDB::BreakpointDB ()
Definition at line 63 of file GDBServer.cpp.
References instrbrkpt_.
Member Function Documentation
get()
etiss::uint32 etiss::plugin::gdb::BreakpointDB::get (etiss::uint64 addr) inline
Definition at line 84 of file GDBServer.h.
References instrbrkpt_, and unlikely.
Referenced by etiss::plugin::gdb::Server::handlePacket(), and etiss::plugin::gdb::Server::preInstructionCallback().
isEmpty()
bool etiss::plugin::gdb::BreakpointDB::isEmpty () inline
Definition at line 83 of file GDBServer.h.
References instrbrkpt_.
Referenced by etiss::plugin::gdb::Server::preInstructionCallback().
set()
void BreakpointDB::set (etiss::uint64 addr, etiss::uint32 val)
Definition at line 68 of file GDBServer.cpp.
References instrbrkpt_.
Referenced by etiss::plugin::gdb::Server::handlePacket().
Member Data Documentation
instrbrkpt_
etiss::uint32*** * etiss::plugin::gdb::BreakpointDB::instrbrkpt_ private
important: index maps are reversed to instruction pointer e.g pointer(0x0102030405060708) [POINTER != ADDRESS] -> instrbrkpt_[0x0708][0x0506][0x0304][0x0201]
Definition at line 109 of file GDBServer.h.
Referenced by BreakpointDB(), get(), isEmpty(), and set().
The documentation for this class was generated from the following files:
/home/travis/build/tum-ei-eda/etiss/include/etiss/IntegratedLibrary/gdb/GDBServer.h
/home/travis/build/tum-ei-eda/etiss/src/IntegratedLibrary/gdb/GDBServer.cpp