ETISS 0.8.0: /home/travis/build/tum-ei-eda/etiss/src/CPUArch.cpp File Reference
CPUArch.cpp File Reference
implementation of etiss/CPUArch.h
#include "etiss/CPUArch.h"
#include <iostream>
#include "etiss/CPUCore.h"
Functions
static void CPUArch_finalizeInstrSet (etiss::instr::InstructionSet *set)
void ETISS_signalChangedRegisterValue (ETISS_CPU *cpu, const char *registerName)
Detailed Description
implementation of etiss/CPUArch.h
Copyright
Copyright 2018 Infineon Technologies AG
This file is part of ETISS tool, see https://gitlab.lrz.de/de-tum-ei-eda-open/etiss.
The initial version of this software has been created with the funding support by the German Federal
Ministry of Education and Research (BMBF) in the project EffektiV under grant 01IS13022.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and
the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse
or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
Author
Marc Greim marc..nosp@m.grei.nosp@m.m@myt.nosp@m.um.d.nosp@m.e, Chair of Electronic Design Automation, TUM
Date
July 29, 2014
Version
0.1
Definition in file CPUArch.cpp.
Function Documentation
CPUArch_finalizeInstrSet()
static void CPUArch_finalizeInstrSet (etiss::instr::InstructionSet * set) static
TODO? ensure instruction pointer update
Definition at line 153 of file CPUArch.cpp.
References etiss::RegisterSet::add(), etiss::instr::Instruction::addCallback(), etiss::CodePart::code(), etiss::CodePart::getAffectedRegisters(), etiss::CodePart::INITIALREQUIRED, etiss::CodeSet::prepend(), and etiss::instr::Instruction::presentBuiltinGroups().
Referenced by etiss::CPUArch::finalizeInstrSet().
ETISS_signalChangedRegisterValue()
void ETISS_signalChangedRegisterValue (ETISS_CPU * cpu, const char * registerName)
Definition at line 189 of file CPUArch.cpp.
References etiss::CPUArchRegListenerInterface::signalChangedRegisterValue().