ETISS 0.8.0: /home/travis/build/tum-ei-eda/etiss/src/CPUCore.cpp File Reference
CPUCore.cpp File Reference
implementation of etiss/CPUCore.h
#include "etiss/CPUCore.h"
#include "etiss/ETISS.h"
Classes
class LegacyRegisterDevicePluginListener
Functions
static bool verifyJITSizeOf (std::string structname, etiss::int32 expected_size, etiss::JIT *jit, std::string prefix=std::string())
generates and compiles test code for the just in time compiler to check size of basic types
static bool verifyJITPragmaPack (etiss::JIT *jit)
generates test code to check alignment of structures in the just in time compiler
static void etiss_CPUCore_handleException (ETISS_CPU *cpu, etiss::int32 &code, BlockLink *&block_ptr, Translation &translator, CPUArch *arch)
small helper function to handle exceptions.
Variables
int currID = 0
Detailed Description
implementation of etiss/CPUCore.h
Copyright
Copyright 2018 Infineon Technologies AG
This file is part of ETISS tool, see https://gitlab.lrz.de/de-tum-ei-eda-open/etiss.
The initial version of this software has been created with the funding support by the German Federal
Ministry of Education and Research (BMBF) in the project EffektiV under grant 01IS13022.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and
the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse
or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
Author
Marc Greim marc..nosp@m.grei.nosp@m.m@myt.nosp@m.um.d.nosp@m.e, Chair of Electronic Design Automation, TUM
Date
July 29, 2014
Version
0.1
Definition in file CPUCore.cpp.
Function Documentation
etiss_CPUCore_handleException()
static void etiss_CPUCore_handleException (ETISS_CPU * cpu, etiss::int32 & code, BlockLink *& block_ptr, Translation & translator, CPUArch * arch) static
small helper function to handle exceptions.
in most cases the exception is simply passed on to etiss::CPUArch::handleExcpetion()
Definition at line 465 of file CPUCore.cpp.
References etiss::ERROR, etiss::CPUArch::handleException(), etiss::log(), etiss::mm::NOERROR, unlikely, etiss::Translation::unloadBlocks(), and etiss::BlockLink::valid.
Referenced by etiss::CPUCore::execute().
verifyJITPragmaPack()
static bool verifyJITPragmaPack (etiss::JIT * jit) static
generates test code to check alignment of structures in the just in time compiler
Definition at line 375 of file CPUCore.cpp.
References etiss::ERROR, etiss::JIT::free(), etiss::JIT::getFunction(), etiss::jitFiles(), etiss::log(), and etiss::JIT::translate().
Referenced by etiss::CPUCore::execute().
verifyJITSizeOf()
static bool verifyJITSizeOf (std::string structname, etiss::int32 expected_size, etiss::JIT * jit, std::string prefix = std::string()) static
generates and compiles test code for the just in time compiler to check size of basic types
Definition at line 325 of file CPUCore.cpp.
References etiss::ERROR, etiss::JIT::free(), etiss::JIT::getFunction(), etiss::jitFiles(), etiss::log(), and etiss::JIT::translate().
Referenced by etiss::CPUCore::execute().
Variable Documentation
currID
int currID = 0
Definition at line 151 of file CPUCore.cpp.
Referenced by etiss::CPUCore::getNextID().