ETISS 0.8.0: etiss::fault Namespace Reference
etiss::fault Namespace Reference
Namespaces
xml
Classes
class Action
class CPUStateCopyHelper
class Fault
class Injector
class InjectorAddress
class Stressor
class Trigger
Typedefs
typedef std::shared_ptr< Injector > Injector_ptr
typedef uint64_t INT
Functions
void setCoreName (std::string &str)
static int32_t uniqueFaultId ()
static std::map< int32_t, Fault > & faults ()
Variables
int coreIDActuallXML
int x
Typedef Documentation
Injector_ptr
typedef Injector * etiss::fault::Injector_ptr
Definition at line 83 of file Defs.h.
INT
typedef uint64_t etiss::fault::INT
Definition at line 83 of file Fault.h.
Function Documentation
faults()
static std::map<int32_t, Fault>& etiss::fault::faults () static
Definition at line 74 of file Stressor.cpp.
Referenced by etiss::fault::Stressor::addFault(), etiss::fault::Stressor::clear(), etiss_initialize(), etiss::fault::Stressor::firedTrigger(), and etiss::fault::Stressor::loadXML().
setCoreName()
void etiss::fault::setCoreName (std::string & str)
Definition at line 62 of file XML.cpp.
References pugi::xml_node::first_child(), pugi::xml_attribute::name(), pugi::xml_node::name(), name, pugi::xml_attribute::next_attribute(), pugi::xml_node::next_sibling(), pugi::node_null, pugi::node_pcdata, pugi::xml_node::path(), static_assert, pugi::xml_node::type(), and pugi::xml_node::value().
Referenced by etiss::fault::InjectorAddress::isResolved(), etiss::fault::Action::toString(), and etiss::fault::Trigger::toString().
uniqueFaultId()
static int32_t etiss::fault::uniqueFaultId () static
Definition at line 199 of file Fault.cpp.
Referenced by etiss::fault::Fault::Fault().
Variable Documentation
coreIDActuallXML
int etiss::fault::coreIDActuallXML
Definition at line 61 of file XML.cpp.
Referenced by etiss::fault::Stressor::loadXML().
x
int etiss::fault::x
Definition at line 60 of file Injector.cpp.
Referenced by etiss::ObjectPool< etiss::FixedSizeHashMap::Entry >::address(), etiss::jitExtHeaderPaths(), etiss::jitExtHeaders(), etiss::jitExtLibPaths(), and etiss::jitExtLibraries().