ETISS 0.8.0: etiss::py Namespace Reference
etiss::py Namespace Reference
Functions
void init ()
void shutdown ()
Shutdown ETISS.
void console ()
bool supported ()
void runString (std::string s)
void run (std::function< void(void)> func)
void runEXT (std::function< void(void)> func)
std::string evalForString (const char *stmt, bool *ok=nullptr)
Function Documentation
console()
void etiss::py::console ()
Definition at line 465 of file ETISSPython.cpp.
Referenced by etiss_initialize(), and etiss::Initializer::Initializer().
evalForString()
std::string etiss::py::evalForString (const char * stmt, bool * ok = nullptr)
Definition at line 476 of file ETISSPython.cpp.
init()
void etiss::py::init ()
Definition at line 461 of file ETISSPython.cpp.
Referenced by etiss_initialize(), etiss::Initializer::Initializer(), and etiss::interfaces::WishboneBus< BOOLSIG, VECTORSIG, instrBus, flipEndianess, bytewidth, VECTORSIGSTORAGETYPE >::update().
run()
void etiss::py::run (std::function< void(void)> func)
Definition at line 474 of file ETISSPython.cpp.
Referenced by etiss::Initializer::Initializer().
runEXT()
void etiss::py::runEXT (std::function< void(void)> func)
Referenced by etiss::Initializer::Initializer().
runString()
void etiss::py::runString (std::string s)
Definition at line 472 of file ETISSPython.cpp.
Referenced by etiss::Initializer::Initializer().
supported()
bool etiss::py::supported ()
Definition at line 467 of file ETISSPython.cpp.
Referenced by etiss::Initializer::Initializer().