ETISS 0.8.0: /home/travis/build/tum-ei-eda/etiss/src/fpu/softfloat.cpp File Reference
softfloat.cpp File Reference
implements software flot calculation
#include "etiss/fpu/milieu.h"
#include "etiss/jit/fpu/softfloat.h"
#include "softfloat-macros"
#include "softfloat-specialize"
Macros
#define float_raise(X) *etiss_fpu_flags |= (X);
Functions
static int32 roundAndPackInt32 (flag zSign, bits64 absZ, unsigned *etiss_fpu_flags)
static int64 roundAndPackInt64 (flag zSign, bits64 absZ0, bits64 absZ1, unsigned *etiss_fpu_flags)
INLINE bits32 extractFloat32Frac (float32 a)
INLINE int16 extractFloat32Exp (float32 a)
INLINE flag extractFloat32Sign (float32 a)
static void normalizeFloat32Subnormal (bits32 aSig, int16 *zExpPtr, bits32 *zSigPtr)
INLINE float32 packFloat32 (flag zSign, int16 zExp, bits32 zSig)
static float32 roundAndPackFloat32 (flag zSign, int16 zExp, bits32 zSig, unsigned *etiss_fpu_flags)
static float32 normalizeRoundAndPackFloat32 (flag zSign, int16 zExp, bits32 zSig, unsigned *etiss_fpu_flags)
INLINE bits64 extractFloat64Frac (float64 a)
INLINE int16 extractFloat64Exp (float64 a)
INLINE flag extractFloat64Sign (float64 a)
static void normalizeFloat64Subnormal (bits64 aSig, int16 *zExpPtr, bits64 *zSigPtr)
INLINE float64 packFloat64 (flag zSign, int16 zExp, bits64 zSig)
static float64 roundAndPackFloat64 (flag zSign, int16 zExp, bits64 zSig, unsigned *etiss_fpu_flags)
static float64 normalizeRoundAndPackFloat64 (flag zSign, int16 zExp, bits64 zSig, unsigned *etiss_fpu_flags)
float32 int32_to_float32 (int32 a, unsigned *etiss_fpu_flags)
float64 int32_to_float64 (int32 a)
float32 int64_to_float32 (int64 a, unsigned *etiss_fpu_flags)
float64 int64_to_float64 (int64 a, unsigned *etiss_fpu_flags)
int32 float32_to_int32 (float32 a, unsigned *etiss_fpu_flags)
int32 float32_to_int32_round_to_zero (float32 a, unsigned *etiss_fpu_flags)
int64 float32_to_int64 (float32 a, unsigned *etiss_fpu_flags)
int64 float32_to_int64_round_to_zero (float32 a, unsigned *etiss_fpu_flags)
float64 float32_to_float64 (float32 a, unsigned *etiss_fpu_flags)
float32 float32_round_to_int (float32 a, unsigned *etiss_fpu_flags)
static float32 addFloat32Sigs (float32 a, float32 b, flag zSign, unsigned *etiss_fpu_flags)
static float32 subFloat32Sigs (float32 a, float32 b, flag zSign, unsigned *etiss_fpu_flags)
float32 float32_add (float32 a, float32 b, unsigned *etiss_fpu_flags)
float32 float32_sub (float32 a, float32 b, unsigned *etiss_fpu_flags)
float32 float32_mul (float32 a, float32 b, unsigned *etiss_fpu_flags)
float32 float32_div (float32 a, float32 b, unsigned *etiss_fpu_flags)
float32 float32_rem (float32 a, float32 b, unsigned *etiss_fpu_flags)
float32 float32_sqrt (float32 a, unsigned *etiss_fpu_flags)
flag float32_eq (float32 a, float32 b, unsigned *etiss_fpu_flags)
flag float32_le (float32 a, float32 b, unsigned *etiss_fpu_flags)
flag float32_lt (float32 a, float32 b, unsigned *etiss_fpu_flags)
flag float32_eq_signaling (float32 a, float32 b, unsigned *etiss_fpu_flags)
flag float32_le_quiet (float32 a, float32 b, unsigned *etiss_fpu_flags)
flag float32_lt_quiet (float32 a, float32 b, unsigned *etiss_fpu_flags)
int32 float64_to_int32 (float64 a, unsigned *etiss_fpu_flags)
int32 float64_to_int32_round_to_zero (float64 a, unsigned *etiss_fpu_flags)
int64 float64_to_int64 (float64 a, unsigned *etiss_fpu_flags)
int64 float64_to_int64_round_to_zero (float64 a, unsigned *etiss_fpu_flags)
float32 float64_to_float32 (float64 a, unsigned *etiss_fpu_flags)
float64 float64_round_to_int (float64 a, unsigned *etiss_fpu_flags)
static float64 addFloat64Sigs (float64 a, float64 b, flag zSign, unsigned *etiss_fpu_flags)
static float64 subFloat64Sigs (float64 a, float64 b, flag zSign, unsigned *etiss_fpu_flags)
float64 float64_add (float64 a, float64 b, unsigned *etiss_fpu_flags)
float64 float64_sub (float64 a, float64 b, unsigned *etiss_fpu_flags)
float64 float64_mul (float64 a, float64 b, unsigned *etiss_fpu_flags)
float64 float64_div (float64 a, float64 b, unsigned *etiss_fpu_flags)
float64 float64_rem (float64 a, float64 b, unsigned *etiss_fpu_flags)
float64 float64_sqrt (float64 a, unsigned *etiss_fpu_flags)
flag float64_eq (float64 a, float64 b, unsigned *etiss_fpu_flags)
flag float64_le (float64 a, float64 b, unsigned *etiss_fpu_flags)
flag float64_lt (float64 a, float64 b, unsigned *etiss_fpu_flags)
flag float64_eq_signaling (float64 a, float64 b, unsigned *etiss_fpu_flags)
flag float64_le_quiet (float64 a, float64 b, unsigned *etiss_fpu_flags)
flag float64_lt_quiet (float64 a, float64 b, unsigned *etiss_fpu_flags)
Variables
int8 float_rounding_mode = float_round_nearest_even
int8 float_exception_flags = 0
Detailed Description
implements software flot calculation
Copyright
This C source file is part of the SoftFloat IEC/IEEE Floating-point Arithmetic Package, Release 2b.
        Written by John R. Hauser.  This work was made possible in part by the
        International Computer Science Institute, located at Suite 600, 1947 Center
        Street, Berkeley, California 94704.  Funding was partially provided by the
        National Science Foundation under grant MIP-9311980.  The original version
        of this code was written as part of a project to build a fixed-point vector
        processor in collaboration with the University of California at Berkeley,
        overseen by Profs. Nelson Morgan and John Wawrzynek.  More information
        is available through the Web page `http://www.cs.berkeley.edu/~jhauser/
        arithmetic/SoftFloat.html'.
        THIS SOFTWARE IS DISTRIBUTED AS IS, FOR FREE.  Although reasonable effort has
        been made to avoid it, THIS SOFTWARE MAY CONTAIN FAULTS THAT WILL AT TIMES
        RESULT IN INCORRECT BEHAVIOR.  USE OF THIS SOFTWARE IS RESTRICTED TO PERSONS
        AND ORGANIZATIONS WHO CAN AND WILL TAKE FULL RESPONSIBILITY FOR ALL LOSSES,
        COSTS, OR OTHER PROBLEMS THEY INCUR DUE TO THE SOFTWARE, AND WHO FURTHERMORE
        EFFECTIVELY INDEMNIFY JOHN HAUSER AND THE INTERNATIONAL COMPUTER SCIENCE
        INSTITUTE (possibly via similar legal warning) AGAINST ALL LOSSES, COSTS, OR
        OTHER PROBLEMS INCURRED BY THEIR CUSTOMERS AND CLIENTS DUE TO THE SOFTWARE.
        Derivative works are acceptable, even for commercial purposes, so long as
        (1) the source code for the derivative work includes prominent notice that
        the work is derivative, and (2) the source code includes prominent notice with
        these four paragraphs for those parts of this code that are retained.
Note
This is a derivative work. The exception flags are now applied to a passed variable (unsigned * etiss_fpu_flags [may never be 0]) instead of calling a function
Author
John R. Hauser (original version)
Marc Greim (changed handling of flags)
Definition in file softfloat.cpp.
Macro Definition Documentation
float_raise
#define float_raise (X) *etiss_fpu_flags |= (X);
Definition at line 72 of file softfloat.cpp.
Referenced by float32_div(), float32_eq(), float32_eq_signaling(), float32_le(), float32_le_quiet(), float32_lt(), float32_lt_quiet(), float32_mul(), float32_rem(), float32_sqrt(), float32_to_int32_round_to_zero(), float32_to_int64(), float32_to_int64_round_to_zero(), float64_div(), float64_eq(), float64_eq_signaling(), float64_le(), float64_le_quiet(), float64_lt(), float64_lt_quiet(), float64_mul(), float64_rem(), float64_sqrt(), float64_to_int32_round_to_zero(), float64_to_int64(), float64_to_int64_round_to_zero(), normalizeRoundAndPackFloat64(), roundAndPackFloat32(), roundAndPackFloat64(), roundAndPackInt32(), roundAndPackInt64(), subFloat32Sigs(), and subFloat64Sigs().
Function Documentation
addFloat32Sigs()
static float32 addFloat32Sigs (float32 a, float32 b, flag zSign, unsigned * etiss_fpu_flags) static
Definition at line 1601 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), packFloat32(), and roundAndPackFloat32().
Referenced by float32_add(), and float32_sub().
addFloat64Sigs()
static float64 addFloat64Sigs (float64 a, float64 b, flag zSign, unsigned * etiss_fpu_flags) static
Definition at line 2643 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), LIT64, packFloat64(), and roundAndPackFloat64().
Referenced by float64_add(), and float64_sub().
extractFloat32Exp()
INLINE int16 extractFloat32Exp (float32 a)
Definition at line 229 of file softfloat.cpp.
Referenced by addFloat32Sigs(), float32_div(), float32_eq(), float32_eq_signaling(), float32_le(), float32_le_quiet(), float32_lt(), float32_lt_quiet(), float32_mul(), float32_rem(), float32_round_to_int(), float32_sqrt(), float32_to_float64(), float32_to_int32(), float32_to_int32_round_to_zero(), float32_to_int64(), float32_to_int64_round_to_zero(), and subFloat32Sigs().
extractFloat32Frac()
INLINE bits32 extractFloat32Frac (float32 a)
Definition at line 223 of file softfloat.cpp.
Referenced by addFloat32Sigs(), float32_div(), float32_eq(), float32_eq_signaling(), float32_le(), float32_le_quiet(), float32_lt(), float32_lt_quiet(), float32_mul(), float32_rem(), float32_round_to_int(), float32_sqrt(), float32_to_float64(), float32_to_int32(), float32_to_int32_round_to_zero(), float32_to_int64(), float32_to_int64_round_to_zero(), and subFloat32Sigs().
extractFloat32Sign()
INLINE flag extractFloat32Sign (float32 a)
Definition at line 235 of file softfloat.cpp.
Referenced by float32_add(), float32_div(), float32_le(), float32_le_quiet(), float32_lt(), float32_lt_quiet(), float32_mul(), float32_rem(), float32_round_to_int(), float32_sqrt(), float32_sub(), float32_to_float64(), float32_to_int32(), float32_to_int32_round_to_zero(), float32_to_int64(), and float32_to_int64_round_to_zero().
extractFloat64Exp()
INLINE int16 extractFloat64Exp (float64 a)
Definition at line 378 of file softfloat.cpp.
Referenced by addFloat64Sigs(), float64_div(), float64_eq(), float64_eq_signaling(), float64_le(), float64_le_quiet(), float64_lt(), float64_lt_quiet(), float64_mul(), float64_rem(), float64_round_to_int(), float64_sqrt(), float64_to_float32(), float64_to_int32(), float64_to_int32_round_to_zero(), float64_to_int64(), float64_to_int64_round_to_zero(), and subFloat64Sigs().
extractFloat64Frac()
INLINE bits64 extractFloat64Frac (float64 a)
Definition at line 372 of file softfloat.cpp.
References LIT64.
Referenced by addFloat64Sigs(), float64_div(), float64_eq(), float64_eq_signaling(), float64_le(), float64_le_quiet(), float64_lt(), float64_lt_quiet(), float64_mul(), float64_rem(), float64_round_to_int(), float64_sqrt(), float64_to_float32(), float64_to_int32(), float64_to_int32_round_to_zero(), float64_to_int64(), float64_to_int64_round_to_zero(), and subFloat64Sigs().
extractFloat64Sign()
INLINE flag extractFloat64Sign (float64 a)
Definition at line 384 of file softfloat.cpp.
Referenced by float64_add(), float64_div(), float64_le(), float64_le_quiet(), float64_lt(), float64_lt_quiet(), float64_mul(), float64_rem(), float64_round_to_int(), float64_sqrt(), float64_sub(), float64_to_float32(), float64_to_int32(), float64_to_int32_round_to_zero(), float64_to_int64(), and float64_to_int64_round_to_zero().
float32_add()
float32 float32_add (float32 a, float32 b, unsigned * etiss_fpu_flags)
Definition at line 1773 of file softfloat.cpp.
References addFloat32Sigs(), extractFloat32Sign(), and subFloat32Sigs().
Referenced by timeFunctionVariety().
float32_div()
float32 float32_div (float32 a, float32 b, unsigned * etiss_fpu_flags)
Definition at line 1887 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_divbyzero, float_flag_invalid, float_raise, normalizeFloat32Subnormal(), packFloat32(), and roundAndPackFloat32().
Referenced by timeFunctionVariety().
float32_eq()
flag float32_eq (float32 a, float32 b, unsigned * etiss_fpu_flags)
Definition at line 2143 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), float32_is_signaling_nan(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_eq_signaling()
flag float32_eq_signaling (float32 a, float32 b, unsigned * etiss_fpu_flags)
Definition at line 2212 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_le()
flag float32_le (float32 a, float32 b, unsigned * etiss_fpu_flags)
Definition at line 2165 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_le_quiet()
flag float32_le_quiet (float32 a, float32 b, unsigned * etiss_fpu_flags)
Definition at line 2231 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float32_is_signaling_nan(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_lt()
flag float32_lt (float32 a, float32 b, unsigned * etiss_fpu_flags)
Definition at line 2188 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_lt_quiet()
flag float32_lt_quiet (float32 a, float32 b, unsigned * etiss_fpu_flags)
Definition at line 2259 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float32_is_signaling_nan(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_mul()
float32 float32_mul (float32 a, float32 b, unsigned * etiss_fpu_flags)
Definition at line 1817 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_invalid, float_raise, normalizeFloat32Subnormal(), packFloat32(), and roundAndPackFloat32().
Referenced by timeFunctionVariety().
float32_rem()
float32 float32_rem (float32 a, float32 b, unsigned * etiss_fpu_flags)
Definition at line 1961 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_invalid, float_raise, normalizeFloat32Subnormal(), and normalizeRoundAndPackFloat32().
Referenced by timeFunctionVariety().
float32_round_to_int()
float32 float32_round_to_int (float32 a, unsigned * etiss_fpu_flags)
Definition at line 1531 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_inexact, float_round_down, float_round_nearest_even, float_round_to_zero, float_round_up, float_rounding_mode, packFloat32(), and roundingMode.
Referenced by timeFunctionVariety().
float32_sqrt()
float32 float32_sqrt (float32 a, unsigned * etiss_fpu_flags)
Definition at line 2080 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_invalid, float_raise, normalizeFloat32Subnormal(), and roundAndPackFloat32().
Referenced by timeFunctionVariety().
float32_sub()
float32 float32_sub (float32 a, float32 b, unsigned * etiss_fpu_flags)
Definition at line 1795 of file softfloat.cpp.
References addFloat32Sigs(), extractFloat32Sign(), and subFloat32Sigs().
Referenced by timeFunctionVariety().
float32_to_float64()
float64 float32_to_float64 (float32 a, unsigned * etiss_fpu_flags)
Definition at line 1427 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), LIT64, normalizeFloat32Subnormal(), and packFloat64().
Referenced by timeFunctionVariety().
float32_to_int32()
int32 float32_to_int32 (float32 a, unsigned * etiss_fpu_flags)
Definition at line 1260 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), and roundAndPackInt32().
Referenced by timeFunctionVariety().
float32_to_int32_round_to_zero()
int32 float32_to_int32_round_to_zero (float32 a, unsigned * etiss_fpu_flags)
Definition at line 1292 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_inexact, float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_to_int64()
int64 float32_to_int64 (float32 a, unsigned * etiss_fpu_flags)
Definition at line 1340 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_invalid, float_raise, LIT64, and roundAndPackInt64().
Referenced by timeFunctionVariety().
float32_to_int64_round_to_zero()
int64 float32_to_int64_round_to_zero (float32 a, unsigned * etiss_fpu_flags)
Definition at line 1378 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_inexact, float_flag_invalid, float_raise, and LIT64.
Referenced by timeFunctionVariety().
float64_add()
float64 float64_add (float64 a, float64 b, unsigned * etiss_fpu_flags)
Definition at line 2815 of file softfloat.cpp.
References addFloat64Sigs(), extractFloat64Sign(), and subFloat64Sigs().
Referenced by timeFunctionVariety().
float64_div()
float64 float64_div (float64 a, float64 b, unsigned * etiss_fpu_flags)
Definition at line 2927 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_divbyzero, float_flag_invalid, float_raise, LIT64, normalizeFloat64Subnormal(), packFloat64(), and roundAndPackFloat64().
Referenced by timeFunctionVariety().
float64_eq()
flag float64_eq (float64 a, float64 b, unsigned * etiss_fpu_flags)
Definition at line 3171 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), float64_is_signaling_nan(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float64_eq_signaling()
flag float64_eq_signaling (float64 a, float64 b, unsigned * etiss_fpu_flags)
Definition at line 3240 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float64_le()
flag float64_le (float64 a, float64 b, unsigned * etiss_fpu_flags)
Definition at line 3193 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float64_le_quiet()
flag float64_le_quiet (float64 a, float64 b, unsigned * etiss_fpu_flags)
Definition at line 3259 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float64_is_signaling_nan(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float64_lt()
flag float64_lt (float64 a, float64 b, unsigned * etiss_fpu_flags)
Definition at line 3216 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float64_lt_quiet()
flag float64_lt_quiet (float64 a, float64 b, unsigned * etiss_fpu_flags)
Definition at line 3287 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float64_is_signaling_nan(), float_flag_divbyzero, float_flag_inexact, float_flag_invalid, float_raise, float_round_down, float_round_nearest_even, float_round_to_zero, float_round_up, float_rounding_mode, LIT64, packFloat32(), packFloat64(), roundAndPackFloat32(), roundAndPackFloat64(), roundAndPackInt32(), roundAndPackInt64(), and roundingMode.
Referenced by timeFunctionVariety().
float64_mul()
float64 float64_mul (float64 a, float64 b, unsigned * etiss_fpu_flags)
Definition at line 2859 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_invalid, float_raise, LIT64, normalizeFloat64Subnormal(), packFloat64(), and roundAndPackFloat64().
Referenced by timeFunctionVariety().
float64_rem()
float64 float64_rem (float64 a, float64 b, unsigned * etiss_fpu_flags)
Definition at line 3010 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_invalid, float_raise, LIT64, normalizeFloat64Subnormal(), and normalizeRoundAndPackFloat64().
Referenced by timeFunctionVariety().
float64_round_to_int()
float64 float64_round_to_int (float64 a, unsigned * etiss_fpu_flags)
Definition at line 2573 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_inexact, float_round_down, float_round_nearest_even, float_round_to_zero, float_round_up, float_rounding_mode, LIT64, packFloat64(), and roundingMode.
Referenced by timeFunctionVariety().
float64_sqrt()
float64 float64_sqrt (float64 a, unsigned * etiss_fpu_flags)
Definition at line 3111 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_invalid, float_raise, LIT64, normalizeFloat64Subnormal(), and roundAndPackFloat64().
Referenced by timeFunctionVariety().
float64_sub()
float64 float64_sub (float64 a, float64 b, unsigned * etiss_fpu_flags)
Definition at line 2837 of file softfloat.cpp.
References addFloat64Sigs(), extractFloat64Sign(), and subFloat64Sigs().
Referenced by timeFunctionVariety().
float64_to_float32()
float32 float64_to_float32 (float64 a, unsigned * etiss_fpu_flags)
Definition at line 2468 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), LIT64, normalizeFloat64Subnormal(), packFloat32(), and roundAndPackFloat32().
Referenced by timeFunctionVariety().
float64_to_int32()
int32 float64_to_int32 (float64 a, unsigned * etiss_fpu_flags)
Definition at line 2289 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), LIT64, and roundAndPackInt32().
Referenced by timeFunctionVariety().
float64_to_int32_round_to_zero()
int32 float64_to_int32_round_to_zero (float64 a, unsigned * etiss_fpu_flags)
Definition at line 2318 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_inexact, float_flag_invalid, float_raise, and LIT64.
Referenced by timeFunctionVariety().
float64_to_int64()
int64 float64_to_int64 (float64 a, unsigned * etiss_fpu_flags)
Definition at line 2370 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_invalid, float_raise, LIT64, and roundAndPackInt64().
Referenced by timeFunctionVariety().
float64_to_int64_round_to_zero()
int64 float64_to_int64_round_to_zero (float64 a, unsigned * etiss_fpu_flags)
Definition at line 2413 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_inexact, float_flag_invalid, float_raise, and LIT64.
Referenced by timeFunctionVariety().
int32_to_float32()
float32 int32_to_float32 (int32 a, unsigned * etiss_fpu_flags)
Definition at line 1042 of file softfloat.cpp.
References normalizeRoundAndPackFloat32(), and packFloat32().
Referenced by timeFunctionVariety().
int32_to_float64()
float64 int32_to_float64 (int32 a)
Definition at line 1060 of file softfloat.cpp.
References packFloat64().
Referenced by timeFunctionVariety().
int64_to_float32()
float32 int64_to_float32 (int64 a, unsigned * etiss_fpu_flags)
Definition at line 1135 of file softfloat.cpp.
References packFloat32(), and roundAndPackFloat32().
Referenced by timeFunctionVariety().
int64_to_float64()
float64 int64_to_float64 (int64 a, unsigned * etiss_fpu_flags)
Definition at line 1172 of file softfloat.cpp.
References LIT64, normalizeRoundAndPackFloat64(), and packFloat64().
Referenced by timeFunctionVariety().
normalizeFloat32Subnormal()
static void normalizeFloat32Subnormal (bits32 aSig, int16 * zExpPtr, bits32 * zSigPtr) static
Definition at line 244 of file softfloat.cpp.
Referenced by float32_div(), float32_mul(), float32_rem(), float32_sqrt(), and float32_to_float64().
normalizeFloat64Subnormal()
static void normalizeFloat64Subnormal (bits64 aSig, int16 * zExpPtr, bits64 * zSigPtr) static
Definition at line 393 of file softfloat.cpp.
Referenced by float64_div(), float64_mul(), float64_rem(), float64_sqrt(), and float64_to_float32().
normalizeRoundAndPackFloat32()
static float32 normalizeRoundAndPackFloat32 (flag zSign, int16 zExp, bits32 zSig, unsigned * etiss_fpu_flags) static
Definition at line 360 of file softfloat.cpp.
References roundAndPackFloat32().
Referenced by float32_rem(), int32_to_float32(), and subFloat32Sigs().
normalizeRoundAndPackFloat64()
static float64 normalizeRoundAndPackFloat64 (flag zSign, int16 zExp, bits64 zSig, unsigned * etiss_fpu_flags) static
Definition at line 509 of file softfloat.cpp.
References float_detect_tininess, float_flag_inexact, float_flag_overflow, float_flag_underflow, float_raise, float_round_down, float_round_nearest_even, float_round_to_zero, float_round_up, float_rounding_mode, float_tininess_before_rounding, INLINE, LIT64, roundAndPackFloat64(), roundingMode, and roundingPrecision.
Referenced by float64_rem(), int64_to_float64(), and subFloat64Sigs().
packFloat32()
INLINE float32 packFloat32 (flag zSign, int16 zExp, bits32 zSig)
Definition at line 264 of file softfloat.cpp.
Referenced by addFloat32Sigs(), float32_div(), float32_mul(), float32_round_to_int(), float64_lt_quiet(), float64_to_float32(), int32_to_float32(), int64_to_float32(), roundAndPackFloat32(), and subFloat32Sigs().
packFloat64()
INLINE float64 packFloat64 (flag zSign, int16 zExp, bits64 zSig)
Definition at line 413 of file softfloat.cpp.
Referenced by addFloat64Sigs(), float32_to_float64(), float64_div(), float64_lt_quiet(), float64_mul(), float64_round_to_int(), int32_to_float64(), int64_to_float64(), roundAndPackFloat64(), and subFloat64Sigs().
roundAndPackFloat32()
static float32 roundAndPackFloat32 (flag zSign, int16 zExp, bits32 zSig, unsigned * etiss_fpu_flags) static
Definition at line 292 of file softfloat.cpp.
References float_detect_tininess, float_flag_inexact, float_flag_overflow, float_flag_underflow, float_raise, float_round_down, float_round_nearest_even, float_round_to_zero, float_round_up, float_rounding_mode, float_tininess_before_rounding, packFloat32(), and roundingMode.
Referenced by addFloat32Sigs(), float32_div(), float32_mul(), float32_sqrt(), float64_lt_quiet(), float64_to_float32(), int64_to_float32(), and normalizeRoundAndPackFloat32().
roundAndPackFloat64()
static float64 roundAndPackFloat64 (flag zSign, int16 zExp, bits64 zSig, unsigned * etiss_fpu_flags) static
Definition at line 441 of file softfloat.cpp.
References float_detect_tininess, float_flag_inexact, float_flag_overflow, float_flag_underflow, float_raise, float_round_down, float_round_nearest_even, float_round_to_zero, float_round_up, float_rounding_mode, float_tininess_before_rounding, LIT64, packFloat64(), and roundingMode.
Referenced by addFloat64Sigs(), float64_div(), float64_lt_quiet(), float64_mul(), float64_sqrt(), and normalizeRoundAndPackFloat64().
roundAndPackInt32()
static int32 roundAndPackInt32 (flag zSign, bits64 absZ, unsigned * etiss_fpu_flags) static
Definition at line 112 of file softfloat.cpp.
References float_flag_inexact, float_flag_invalid, float_raise, float_round_down, float_round_nearest_even, float_round_to_zero, float_round_up, float_rounding_mode, and roundingMode.
Referenced by float32_to_int32(), float64_lt_quiet(), and float64_to_int32().
roundAndPackInt64()
static int64 roundAndPackInt64 (flag zSign, bits64 absZ0, bits64 absZ1, unsigned * etiss_fpu_flags) static
Definition at line 171 of file softfloat.cpp.
References float_flag_inexact, float_flag_invalid, float_raise, float_round_down, float_round_nearest_even, float_round_to_zero, float_round_up, float_rounding_mode, LIT64, and roundingMode.
Referenced by float32_to_int64(), float64_lt_quiet(), and float64_to_int64().
subFloat32Sigs()
static float32 subFloat32Sigs (float32 a, float32 b, flag zSign, unsigned * etiss_fpu_flags) static
Definition at line 1686 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), float_flag_invalid, float_raise, float_round_down, normalizeRoundAndPackFloat32(), and packFloat32().
Referenced by float32_add(), and float32_sub().
subFloat64Sigs()
static float64 subFloat64Sigs (float64 a, float64 b, flag zSign, unsigned * etiss_fpu_flags) static
Definition at line 2728 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), float_flag_invalid, float_raise, float_round_down, LIT64, normalizeRoundAndPackFloat64(), and packFloat64().
Referenced by float64_add(), and float64_sub().
Variable Documentation
float_exception_flags
int8 float_exception_flags = 0
Definition at line 79 of file softfloat.cpp.
float_rounding_mode
int8 float_rounding_mode = float_round_nearest_even
Definition at line 78 of file softfloat.cpp.
Referenced by float32_round_to_int(), float64_lt_quiet(), float64_round_to_int(), normalizeRoundAndPackFloat64(), roundAndPackFloat32(), roundAndPackFloat64(), roundAndPackInt32(), roundAndPackInt64(), and timeFunctionVariety().