ETISS 0.8.0: /home/travis/build/tum-ei-eda/etiss/include_c/etiss/jit/fpu/softfloat.h File Reference
softfloat.h File Reference
#include "etiss/jit/types.h"
Typedefs
typedef etiss_uint32 float32
typedef etiss_uint64 float64
Enumerations
enum { float_tininess_after_rounding = 0, float_tininess_before_rounding = 1 }
enum { float_round_nearest_even = 0, float_round_down = 1, float_round_up = 2, float_round_to_zero = 3 }
enum {
float_flag_invalid = 1, float_flag_divbyzero = 4, float_flag_overflow = 8, float_flag_underflow = 16,
float_flag_inexact = 32
}
Functions
void float_raise (signed char)
float32 int32_to_float32 (etiss_int32, unsigned *etiss_fpu_flags)
float64 int32_to_float64 (etiss_int32)
float32 int64_to_float32 (etiss_int64, unsigned *etiss_fpu_flags)
float64 int64_to_float64 (etiss_int64, unsigned *etiss_fpu_flags)
etiss_int32 float32_to_int32 (float32, unsigned *etiss_fpu_flags)
etiss_int32 float32_to_int32_round_to_zero (float32, unsigned *etiss_fpu_flags)
etiss_int64 float32_to_int64 (float32, unsigned *etiss_fpu_flags)
etiss_int64 float32_to_int64_round_to_zero (float32, unsigned *etiss_fpu_flags)
float64 float32_to_float64 (float32, unsigned *etiss_fpu_flags)
float32 float32_round_to_int (float32, unsigned *etiss_fpu_flags)
float32 float32_add (float32, float32, unsigned *etiss_fpu_flags)
float32 float32_sub (float32, float32, unsigned *etiss_fpu_flags)
float32 float32_mul (float32, float32, unsigned *etiss_fpu_flags)
float32 float32_div (float32, float32, unsigned *etiss_fpu_flags)
float32 float32_rem (float32, float32, unsigned *etiss_fpu_flags)
float32 float32_sqrt (float32, unsigned *etiss_fpu_flags)
char float32_eq (float32, float32, unsigned *etiss_fpu_flags)
char float32_le (float32, float32, unsigned *etiss_fpu_flags)
char float32_lt (float32, float32, unsigned *etiss_fpu_flags)
char float32_eq_signaling (float32, float32, unsigned *etiss_fpu_flags)
char float32_le_quiet (float32, float32, unsigned *etiss_fpu_flags)
char float32_lt_quiet (float32, float32, unsigned *etiss_fpu_flags)
char float32_is_signaling_nan (float32)
etiss_int32 float64_to_int32 (float64, unsigned *etiss_fpu_flags)
etiss_int32 float64_to_int32_round_to_zero (float64, unsigned *etiss_fpu_flags)
etiss_int64 float64_to_int64 (float64, unsigned *etiss_fpu_flags)
etiss_int64 float64_to_int64_round_to_zero (float64, unsigned *etiss_fpu_flags)
float32 float64_to_float32 (float64, unsigned *etiss_fpu_flags)
float64 float64_round_to_int (float64, unsigned *etiss_fpu_flags)
float64 float64_add (float64, float64, unsigned *etiss_fpu_flags)
float64 float64_sub (float64, float64, unsigned *etiss_fpu_flags)
float64 float64_mul (float64, float64, unsigned *etiss_fpu_flags)
float64 float64_div (float64, float64, unsigned *etiss_fpu_flags)
float64 float64_rem (float64, float64, unsigned *etiss_fpu_flags)
float64 float64_sqrt (float64, unsigned *etiss_fpu_flags)
char float64_eq (float64, float64, unsigned *etiss_fpu_flags)
char float64_le (float64, float64, unsigned *etiss_fpu_flags)
char float64_lt (float64, float64, unsigned *etiss_fpu_flags)
char float64_eq_signaling (float64, float64, unsigned *etiss_fpu_flags)
char float64_le_quiet (float64, float64, unsigned *etiss_fpu_flags)
char float64_lt_quiet (float64, float64, unsigned *etiss_fpu_flags)
char float64_is_signaling_nan (float64)
Variables
signed char float_detect_tininess
signed char float_rounding_mode
signed char float_exception_flags
Typedef Documentation
float32
typedef etiss_uint32 float32
Copyright
This C header file is part of the SoftFloat IEC/IEEE Floating-point Arithmetic Package, Release 2b.
Written by John R. Hauser.  This work was made possible in part by the
International Computer Science Institute, located at Suite 600, 1947 Center
Street, Berkeley, California 94704.  Funding was partially provided by the
National Science Foundation under grant MIP-9311980.  The original version
of this code was written as part of a project to build a fixed-point vector
processor in collaboration with the University of California at Berkeley,
overseen by Profs. Nelson Morgan and John Wawrzynek.  More information
is available through the Web page `http://www.cs.berkeley.edu/~jhauser/
arithmetic/SoftFloat.html'.
THIS SOFTWARE IS DISTRIBUTED AS IS, FOR FREE.  Although reasonable effort has
been made to avoid it, THIS SOFTWARE MAY CONTAIN FAULTS THAT WILL AT TIMES
RESULT IN INCORRECT BEHAVIOR.  USE OF THIS SOFTWARE IS RESTRICTED TO PERSONS
AND ORGANIZATIONS WHO CAN AND WILL TAKE FULL RESPONSIBILITY FOR ALL LOSSES,
COSTS, OR OTHER PROBLEMS THEY INCUR DUE TO THE SOFTWARE, AND WHO FURTHERMORE
EFFECTIVELY INDEMNIFY JOHN HAUSER AND THE INTERNATIONAL COMPUTER SCIENCE
INSTITUTE (possibly via similar legal warning) AGAINST ALL LOSSES, COSTS, OR
OTHER PROBLEMS INCURRED BY THEIR CUSTOMERS AND CLIENTS DUE TO THE SOFTWARE.
Derivative works are acceptable, even for commercial purposes, so long as
(1) the source code for the derivative work includes prominent notice that
the work is derivative, and (2) the source code includes prominent notice with
these four paragraphs for those parts of this code that are retained.
Definition at line 56 of file softfloat.h.
float64
typedef etiss_uint64 float64
Definition at line 57 of file softfloat.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
float_tininess_after_rounding
float_tininess_before_rounding
Definition at line 76 of file softfloat.h.
anonymous enum
anonymous enum
Enumerator
float_round_nearest_even
float_round_down
float_round_up
float_round_to_zero
Definition at line 86 of file softfloat.h.
anonymous enum
anonymous enum
Enumerator
float_flag_invalid
float_flag_divbyzero
float_flag_overflow
float_flag_underflow
float_flag_inexact
Definition at line 98 of file softfloat.h.
Function Documentation
float32_add()
float32 float32_add (float32 , float32 , unsigned * etiss_fpu_flags)
Definition at line 1773 of file softfloat.cpp.
References addFloat32Sigs(), extractFloat32Sign(), and subFloat32Sigs().
Referenced by timeFunctionVariety().
float32_div()
float32 float32_div (float32 , float32 , unsigned * etiss_fpu_flags)
Definition at line 1887 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_divbyzero, float_flag_invalid, float_raise, normalizeFloat32Subnormal(), packFloat32(), and roundAndPackFloat32().
Referenced by timeFunctionVariety().
float32_eq()
char float32_eq (float32 , float32 , unsigned * etiss_fpu_flags)
Definition at line 2143 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), float32_is_signaling_nan(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_eq_signaling()
char float32_eq_signaling (float32 , float32 , unsigned * etiss_fpu_flags)
Definition at line 2212 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_is_signaling_nan()
char float32_is_signaling_nan (float32)
Referenced by float32_eq(), float32_le_quiet(), and float32_lt_quiet().
float32_le()
char float32_le (float32 , float32 , unsigned * etiss_fpu_flags)
Definition at line 2165 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_le_quiet()
char float32_le_quiet (float32 , float32 , unsigned * etiss_fpu_flags)
Definition at line 2231 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float32_is_signaling_nan(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_lt()
char float32_lt (float32 , float32 , unsigned * etiss_fpu_flags)
Definition at line 2188 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_lt_quiet()
char float32_lt_quiet (float32 , float32 , unsigned * etiss_fpu_flags)
Definition at line 2259 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float32_is_signaling_nan(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_mul()
float32 float32_mul (float32 , float32 , unsigned * etiss_fpu_flags)
Definition at line 1817 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_invalid, float_raise, normalizeFloat32Subnormal(), packFloat32(), and roundAndPackFloat32().
Referenced by timeFunctionVariety().
float32_rem()
float32 float32_rem (float32 , float32 , unsigned * etiss_fpu_flags)
Definition at line 1961 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_invalid, float_raise, normalizeFloat32Subnormal(), and normalizeRoundAndPackFloat32().
Referenced by timeFunctionVariety().
float32_round_to_int()
float32 float32_round_to_int (float32 , unsigned * etiss_fpu_flags)
Definition at line 1531 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_inexact, float_round_down, float_round_nearest_even, float_round_to_zero, float_round_up, float_rounding_mode, packFloat32(), and roundingMode.
Referenced by timeFunctionVariety().
float32_sqrt()
float32 float32_sqrt (float32 , unsigned * etiss_fpu_flags)
Definition at line 2080 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_invalid, float_raise, normalizeFloat32Subnormal(), and roundAndPackFloat32().
Referenced by timeFunctionVariety().
float32_sub()
float32 float32_sub (float32 , float32 , unsigned * etiss_fpu_flags)
Definition at line 1795 of file softfloat.cpp.
References addFloat32Sigs(), extractFloat32Sign(), and subFloat32Sigs().
Referenced by timeFunctionVariety().
float32_to_float64()
float64 float32_to_float64 (float32 , unsigned * etiss_fpu_flags)
Definition at line 1427 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), LIT64, normalizeFloat32Subnormal(), and packFloat64().
Referenced by timeFunctionVariety().
float32_to_int32()
etiss_int32 float32_to_int32 (float32 , unsigned * etiss_fpu_flags)
Definition at line 1260 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), and roundAndPackInt32().
Referenced by timeFunctionVariety().
float32_to_int32_round_to_zero()
etiss_int32 float32_to_int32_round_to_zero (float32 , unsigned * etiss_fpu_flags)
Definition at line 1292 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_inexact, float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float32_to_int64()
etiss_int64 float32_to_int64 (float32 , unsigned * etiss_fpu_flags)
Definition at line 1340 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_invalid, float_raise, LIT64, and roundAndPackInt64().
Referenced by timeFunctionVariety().
float32_to_int64_round_to_zero()
etiss_int64 float32_to_int64_round_to_zero (float32 , unsigned * etiss_fpu_flags)
Definition at line 1378 of file softfloat.cpp.
References extractFloat32Exp(), extractFloat32Frac(), extractFloat32Sign(), float_flag_inexact, float_flag_invalid, float_raise, and LIT64.
Referenced by timeFunctionVariety().
float64_add()
float64 float64_add (float64 , float64 , unsigned * etiss_fpu_flags)
Definition at line 2815 of file softfloat.cpp.
References addFloat64Sigs(), extractFloat64Sign(), and subFloat64Sigs().
Referenced by timeFunctionVariety().
float64_div()
float64 float64_div (float64 , float64 , unsigned * etiss_fpu_flags)
Definition at line 2927 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_divbyzero, float_flag_invalid, float_raise, LIT64, normalizeFloat64Subnormal(), packFloat64(), and roundAndPackFloat64().
Referenced by timeFunctionVariety().
float64_eq()
char float64_eq (float64 , float64 , unsigned * etiss_fpu_flags)
Definition at line 3171 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), float64_is_signaling_nan(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float64_eq_signaling()
char float64_eq_signaling (float64 , float64 , unsigned * etiss_fpu_flags)
Definition at line 3240 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float64_is_signaling_nan()
char float64_is_signaling_nan (float64)
Referenced by float64_eq(), float64_le_quiet(), and float64_lt_quiet().
float64_le()
char float64_le (float64 , float64 , unsigned * etiss_fpu_flags)
Definition at line 3193 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float64_le_quiet()
char float64_le_quiet (float64 , float64 , unsigned * etiss_fpu_flags)
Definition at line 3259 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float64_is_signaling_nan(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float64_lt()
char float64_lt (float64 , float64 , unsigned * etiss_fpu_flags)
Definition at line 3216 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_invalid, and float_raise.
Referenced by timeFunctionVariety().
float64_lt_quiet()
char float64_lt_quiet (float64 , float64 , unsigned * etiss_fpu_flags)
Definition at line 3287 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float64_is_signaling_nan(), float_flag_divbyzero, float_flag_inexact, float_flag_invalid, float_raise, float_round_down, float_round_nearest_even, float_round_to_zero, float_round_up, float_rounding_mode, LIT64, packFloat32(), packFloat64(), roundAndPackFloat32(), roundAndPackFloat64(), roundAndPackInt32(), roundAndPackInt64(), and roundingMode.
Referenced by timeFunctionVariety().
float64_mul()
float64 float64_mul (float64 , float64 , unsigned * etiss_fpu_flags)
Definition at line 2859 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_invalid, float_raise, LIT64, normalizeFloat64Subnormal(), packFloat64(), and roundAndPackFloat64().
Referenced by timeFunctionVariety().
float64_rem()
float64 float64_rem (float64 , float64 , unsigned * etiss_fpu_flags)
Definition at line 3010 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_invalid, float_raise, LIT64, normalizeFloat64Subnormal(), and normalizeRoundAndPackFloat64().
Referenced by timeFunctionVariety().
float64_round_to_int()
float64 float64_round_to_int (float64 , unsigned * etiss_fpu_flags)
Definition at line 2573 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_inexact, float_round_down, float_round_nearest_even, float_round_to_zero, float_round_up, float_rounding_mode, LIT64, packFloat64(), and roundingMode.
Referenced by timeFunctionVariety().
float64_sqrt()
float64 float64_sqrt (float64 , unsigned * etiss_fpu_flags)
Definition at line 3111 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_invalid, float_raise, LIT64, normalizeFloat64Subnormal(), and roundAndPackFloat64().
Referenced by timeFunctionVariety().
float64_sub()
float64 float64_sub (float64 , float64 , unsigned * etiss_fpu_flags)
Definition at line 2837 of file softfloat.cpp.
References addFloat64Sigs(), extractFloat64Sign(), and subFloat64Sigs().
Referenced by timeFunctionVariety().
float64_to_float32()
float32 float64_to_float32 (float64 , unsigned * etiss_fpu_flags)
Definition at line 2468 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), LIT64, normalizeFloat64Subnormal(), packFloat32(), and roundAndPackFloat32().
Referenced by timeFunctionVariety().
float64_to_int32()
etiss_int32 float64_to_int32 (float64 , unsigned * etiss_fpu_flags)
Definition at line 2289 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), LIT64, and roundAndPackInt32().
Referenced by timeFunctionVariety().
float64_to_int32_round_to_zero()
etiss_int32 float64_to_int32_round_to_zero (float64 , unsigned * etiss_fpu_flags)
Definition at line 2318 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_inexact, float_flag_invalid, float_raise, and LIT64.
Referenced by timeFunctionVariety().
float64_to_int64()
etiss_int64 float64_to_int64 (float64 , unsigned * etiss_fpu_flags)
Definition at line 2370 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_invalid, float_raise, LIT64, and roundAndPackInt64().
Referenced by timeFunctionVariety().
float64_to_int64_round_to_zero()
etiss_int64 float64_to_int64_round_to_zero (float64 , unsigned * etiss_fpu_flags)
Definition at line 2413 of file softfloat.cpp.
References extractFloat64Exp(), extractFloat64Frac(), extractFloat64Sign(), float_flag_inexact, float_flag_invalid, float_raise, and LIT64.
Referenced by timeFunctionVariety().
float_raise()
void float_raise (signed char)
int32_to_float32()
float32 int32_to_float32 (etiss_int32 , unsigned * etiss_fpu_flags)
Definition at line 1042 of file softfloat.cpp.
References normalizeRoundAndPackFloat32(), and packFloat32().
Referenced by timeFunctionVariety().
int32_to_float64()
float64 int32_to_float64 (etiss_int32)
Definition at line 1060 of file softfloat.cpp.
References packFloat64().
Referenced by timeFunctionVariety().
int64_to_float32()
float32 int64_to_float32 (etiss_int64 , unsigned * etiss_fpu_flags)
Definition at line 1135 of file softfloat.cpp.
References packFloat32(), and roundAndPackFloat32().
Referenced by timeFunctionVariety().
int64_to_float64()
float64 int64_to_float64 (etiss_int64 , unsigned * etiss_fpu_flags)
Definition at line 1172 of file softfloat.cpp.
References LIT64, normalizeRoundAndPackFloat64(), and packFloat64().
Referenced by timeFunctionVariety().
Variable Documentation
float_detect_tininess
signed char float_detect_tininess
Referenced by normalizeRoundAndPackFloat64(), roundAndPackFloat32(), roundAndPackFloat64(), and timeFunctionVariety().
float_exception_flags
signed char float_exception_flags
Definition at line 79 of file softfloat.cpp.
float_rounding_mode
signed char float_rounding_mode
Definition at line 78 of file softfloat.cpp.
Referenced by float32_round_to_int(), float64_lt_quiet(), float64_round_to_int(), normalizeRoundAndPackFloat64(), roundAndPackFloat32(), roundAndPackFloat64(), roundAndPackInt32(), roundAndPackInt64(), and timeFunctionVariety().