ETISS 0.8.0: ETISS_System Struct Reference
ETISS_System Struct Reference
memory access and time synchronization functions.
#include <System.h>
Public Attributes
etiss_int32(* iread)(void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint32 length)
used to simulate an instruction fetch.
etiss_int32(* iwrite)(void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
write instruction data over instruction bus
etiss_int32(* dread)(void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
read data
etiss_int32(* dwrite)(void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
write data
etiss_int32(* dbg_read)(void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
direct debug read
etiss_int32(* dbg_write)(void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
direct debug write
void(* syncTime)(void *handle, ETISS_CPU *cpu)
called after a block to synchronize the time
void * handle
custom handle that will be passed to the functions of this structure
Detailed Description
memory access and time synchronization functions.
the "handle" parameter passed on a function call is always the "handle" variable of the structure.
to increase performance it is recommended to implement this structure directly. For convinience a etiss::System class is available (include/System.h) that can be extended and which will be automatically wrapped in an ETISS_System structure. NOTE: this structure must be packed {#pragma pack(push, 1)}
See also
include/SystemWrapper.h
src/SystemWrapper.cpp
Definition at line 77 of file System.h.
Member Data Documentation
dbg_read
etiss_int32(* ETISS_System::dbg_read) (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
direct debug read
Definition at line 104 of file System.h.
Referenced by etiss::plugin::MemoryDeviceMapper::dbg_read(), etiss::plugin::dbg_read(), etiss::mm::dbg_read(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dbg_read_(), gdb_system_call_dbg_read(), etiss::plugin::gdb::Server::handlePacket(), etiss::plugin::fault::SwitchSystem::iread(), etiss::interfaces::Delegate::read(), etiss::Translation::translateBlock(), etiss::plugin::Logger::wrap(), etiss::mm::DMMUWrapper::wrap(), etiss::plugin::gdb::Server::wrap(), and etiss::wrap().
dbg_write
etiss_int32(* ETISS_System::dbg_write) (void *handle, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
direct debug write
Definition at line 108 of file System.h.
Referenced by etiss::plugin::MemoryDeviceMapper::dbg_write(), etiss::plugin::dbg_write(), etiss::mm::dbg_write(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dbg_write_(), gdb_system_call_dbg_write(), etiss::plugin::gdb::Server::handlePacket(), etiss::plugin::Logger::wrap(), etiss::mm::DMMUWrapper::wrap(), etiss::plugin::gdb::Server::wrap(), and etiss::wrap().
dread
etiss_int32(* ETISS_System::dread) (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
read data
Definition at line 93 of file System.h.
Referenced by etiss::plugin::fault::SwitchSystem::dread(), etiss::plugin::MemoryDeviceMapper::dread(), etiss::plugin::dread(), etiss::mm::dread(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dread_(), ETISS_System_isvalid(), gdb_system_call_dread(), etiss::plugin::gdb::Server::preMemoryAccessCallback(), etiss::interfaces::Delegate::read(), etiss::plugin::Logger::wrap(), etiss::mm::DMMUWrapper::wrap(), etiss::plugin::gdb::Server::wrap(), and etiss::wrap().
dwrite
etiss_int32(* ETISS_System::dwrite) (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
write data
Definition at line 97 of file System.h.
Referenced by etiss::plugin::fault::SwitchSystem::dwrite(), etiss::plugin::MemoryDeviceMapper::dwrite(), etiss::plugin::dwrite(), etiss::mm::dwrite(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dwrite_(), ETISS_System_isvalid(), gdb_system_call_dwrite(), etiss::plugin::gdb::Server::preMemoryAccessCallback(), etiss::plugin::Logger::wrap(), etiss::mm::DMMUWrapper::wrap(), etiss::plugin::gdb::Server::wrap(), etiss::wrap(), and etiss::interfaces::Delegate::write().
handle
void* ETISS_System::handle
custom handle that will be passed to the functions of this structure
Definition at line 116 of file System.h.
Referenced by etiss::plugin::MemoryDeviceMapper::dbg_read(), etiss::plugin::dbg_read(), etiss::mm::dbg_read(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dbg_read_(), etiss::plugin::MemoryDeviceMapper::dbg_write(), etiss::plugin::dbg_write(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dbg_write_(), etiss::plugin::MemoryDeviceMapper::dread(), etiss::plugin::dread(), etiss::mm::dread(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dread_(), etiss::plugin::MemoryDeviceMapper::dwrite(), etiss::plugin::dwrite(), etiss::mm::dwrite(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dwrite_(), etiss::CPUCore::execute(), gdb_system_call_dbg_read(), gdb_system_call_dbg_write(), gdb_system_call_dread(), gdb_system_call_dwrite(), gdb_system_call_iread(), gdb_system_call_iwrite(), gdb_system_call_syncTime(), etiss::plugin::gdb::Server::handlePacket(), etiss::plugin::MemoryDeviceMapper::iread(), etiss::plugin::iread(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::iread_(), etiss::plugin::MemoryDeviceMapper::iwrite(), etiss::plugin::iwrite(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::iwrite_(), etiss::plugin::gdb::Server::preMemoryAccessCallback(), etiss::interfaces::Delegate::read(), etiss::interfaces::Delegate::syncTime(), etiss::plugin::syncTime(), etiss::mm::syncTime(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::syncTime_(), etiss::Translation::translateBlock(), etiss::plugin::Logger::wrap(), etiss::mm::DMMUWrapper::wrap(), etiss::plugin::gdb::Server::wrap(), etiss::wrap(), and etiss::interfaces::Delegate::write().
iread
etiss_int32(* ETISS_System::iread) (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint32 length)
used to simulate an instruction fetch.
instructions are fetched for translation with dbg_iread(4). this function is not used by default
Definition at line 84 of file System.h.
Referenced by ETISS_System_isvalid(), gdb_system_call_iread(), etiss::mm::iread(), etiss::plugin::fault::SwitchSystem::iread(), etiss::plugin::MemoryDeviceMapper::iread(), etiss::plugin::iread(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::iread_(), etiss::plugin::gdb::Server::preMemoryAccessCallback(), etiss::interfaces::Delegate::read(), etiss::plugin::Logger::wrap(), etiss::mm::DMMUWrapper::wrap(), etiss::plugin::gdb::Server::wrap(), and etiss::wrap().
iwrite
etiss_int32(* ETISS_System::iwrite) (void *handle, ETISS_CPU *cpu, etiss_uint64 addr, etiss_uint8 *buffer, etiss_uint32 length)
write instruction data over instruction bus
Definition at line 88 of file System.h.
Referenced by ETISS_System_isvalid(), gdb_system_call_iwrite(), etiss::plugin::fault::SwitchSystem::iwrite(), etiss::plugin::MemoryDeviceMapper::iwrite(), etiss::mm::iwrite(), etiss::plugin::iwrite(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::iwrite_(), etiss::plugin::gdb::Server::preMemoryAccessCallback(), etiss::plugin::Logger::wrap(), etiss::mm::DMMUWrapper::wrap(), etiss::plugin::gdb::Server::wrap(), etiss::wrap(), and etiss::interfaces::Delegate::write().
syncTime
void(* ETISS_System::syncTime) (void *handle, ETISS_CPU *cpu)
called after a block to synchronize the time
Definition at line 114 of file System.h.
Referenced by ETISS_System_isvalid(), etiss::CPUCore::execute(), gdb_system_call_syncTime(), etiss::interfaces::Delegate::syncTime(), etiss::plugin::syncTime(), etiss::mm::syncTime(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::syncTime_(), etiss::plugin::Logger::wrap(), etiss::mm::DMMUWrapper::wrap(), etiss::plugin::gdb::Server::wrap(), and etiss::wrap().
The documentation for this struct was generated from the following file:
/home/travis/build/tum-ei-eda/etiss/include_c/etiss/jit/System.h