ETISS 0.8.0: document_order_comparator Struct Reference
document_order_comparator Struct Reference
Public Member Functions
bool operator() (const xpath_node &lhs, const xpath_node &rhs) const
Detailed Description
Definition at line 7033 of file pugixml.cpp.
Member Function Documentation
operator()()
bool document_order_comparator::operator() (const xpath_node & lhs, const xpath_node & rhs) const inline
Definition at line 7035 of file pugixml.cpp.
References document_order(), node_height(), node_is_before(), and pugi::xml_node::xml_node().
The documentation for this struct was generated from the following file:
/home/travis/build/tum-ei-eda/etiss/src/fault/xml/pugixml.cpp