ETISS 0.8.0: CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry Struct Reference
CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry Struct Reference
key entry
#include <SimpleIni.h>
Classes
struct KeyOrder
Strict less ordering by name of key only.
struct LoadOrder
Strict less ordering by order, and then name of key.
Public Member Functions
Entry (const SI_CHAR *a_pszItem=NULL, int a_nOrder=0)
Entry (const SI_CHAR *a_pszItem, const SI_CHAR *a_pszComment, int a_nOrder)
Entry (const Entry &rhs)
Entry & operator= (const Entry &rhs)
Public Attributes
const SI_CHAR * pItem
const SI_CHAR * pComment
int nOrder
Detailed Description
template<class SI_CHAR, class SI_STRLESS, class SI_CONVERTER>
struct CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry
key entry
Definition at line 303 of file SimpleIni.h.
Constructor & Destructor Documentation
Entry() [1/3]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::Entry (const SI_CHAR * a_pszItem = NULL, int a_nOrder = 0) inline
Definition at line 309 of file SimpleIni.h.
Entry() [2/3]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::Entry (const SI_CHAR * a_pszItem, const SI_CHAR * a_pszComment, int a_nOrder) inline
Definition at line 310 of file SimpleIni.h.
Entry() [3/3]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::Entry (const Entry & rhs) inline
Definition at line 314 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::operator=().
Member Function Documentation
operator=()
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > Entry& CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::operator= (const Entry & rhs) inline
Definition at line 315 of file SimpleIni.h.
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::nOrder, CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::pComment, and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::pItem.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Converter(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::Entry(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::UsingSpaces(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::FileWriter::Write(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::StringWriter::Write(), and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::OutputWriter::~OutputWriter().
Member Data Documentation
nOrder
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > int CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::nOrder
Definition at line 307 of file SimpleIni.h.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::LoadOrder::operator()(), and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::operator=().
pComment
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > const SI_CHAR* CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::pComment
Definition at line 306 of file SimpleIni.h.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::AddEntry(), and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::operator=().
pItem
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > const SI_CHAR* CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::pItem
Definition at line 305 of file SimpleIni.h.
Referenced by CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::KeyOrder::operator()(), CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::LoadOrder::operator()(), and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Entry::operator=().
The documentation for this struct was generated from the following file:
/home/travis/build/tum-ei-eda/etiss/include/etiss/IntegratedLibrary/SimpleIni/SimpleIni.h